# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a677a3744a8947d25869ce56d3a7e9b411e0bce03167bbfea4750a5c387bdca74b9842848781466bb0b636d4521d7aeca9bb2a55d59960d324da89591684708e

test:
  secret_key_base: dfdc2cd5735becd69751c9a55f68d88629abe04fdec3f956bbd7d73e02abfd0c4305a804ac46b75466220a7d13eb485c06bd99bd15bb06c29d89398a9f4b92a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
